<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanArchitectureTemplate.Domain\CleanArchitectureTemplate.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Productos\Commands\DeleteProducto\" />
    <Folder Include="Features\Productos\Queries\GetAllProductos\" />
    <Folder Include="Features\Productos\Queries\GetProductoById\" />
  </ItemGroup>

</Project>
